def get_end_text():
    end_of_script = 'dim powerpoint As Object = Input.Find(1)\n'
    end_of_script += 'dim camera As Object = Input.Find(2)\n'
    end_of_script += 'dim audio As Object = Input.Find(3)\n'
    end_of_script += 'dim anthem As Object = Input.Find(4)\n'
    end_of_script += 'dim firstReading As Object = Input.Find(6)\n'
    end_of_script += 'dim secondReading As Object = Input.Find(7)\n'
    end_of_script += 'dim firstHymn As Object = Input.Find(9)\n'
    end_of_script += 'dim gospelVerse As Object = Input.Find(10)\n'
    end_of_script += 'dim secondHymn As Object = Input.Find(11)\n'
    end_of_script += 'dim thirdHymn As Object = Input.Find(12)\n'
    end_of_script += 'dim fourthHymn As Object = Input.Find(13)\n'
    end_of_script += 'dim title As Object = Input.Find(14)\n'
    end_of_script += 'dim currentSlide As Integer= Input.Find("NewsHD4.xaml").Text("Headline")\n'
    end_of_script += 'currentSlide = currentSlide + 1\n'
    end_of_script += 'Input.Find("NewsHD4.xaml").Text("Headline") = currentSlide\n\n'

    end_of_script += 'If (currentSlide = firstHymnStart) then firstHymn.function("Restart")\n'
    end_of_script += 'If (currentSlide = secondHymnStart) then secondHymn.function("Restart")\n'
    end_of_script += 'If (currentSlide = thirdHymnStart) then thirdHymn.function("Restart")\n'
    end_of_script += 'If (currentSlide = fourthHymnStart) then fourthHymn.function("Restart")\n\n'

    end_of_script += 'If streaming\n\n'

    end_of_script += 'If (currentSlide = firstReadingStart) then\n'
    end_of_script += 'firstReading.function("Restart")\n'
    end_of_script += 'firstReading.function("Fade")\n'
    end_of_script += 'End If\n\n'

    end_of_script += 'If (currentSlide = secondReadingStart) then\n'
    end_of_script += 'secondReading.function("Restart")\n'
    end_of_script += 'secondReading.function("Fade")\n'
    end_of_script += 'End If\n'
    end_of_script += 'If (currentSlide = serviceEnd) then\n'
    end_of_script += 'powerpoint.function("OverlayInput1Off")\n'
    end_of_script += 'title.function("OverlayInput2Off")\n'
    end_of_script += 'powerpoint.function("Fade")\n\n'
    end_of_script += 'API.function("StopStreaming")\n'
    end_of_script += 'End If\n'
    end_of_script += 'End If\n\n'

    end_of_script += 'If streaming\n'
    end_of_script += 'If ((currentSlide >= firstHymnStart) and currentSlide < (firstHymnStart + firstHymnNumberOfVerses)) then\n'
    end_of_script += 'audio.function("AudioOff")\n'
    end_of_script += 'firstHymn.function("AudioOn")\n'
    end_of_script += 'firstHymn.function("Play")\n'
    end_of_script += 'powerpoint.function("OverlayInput1Off")\n'
    end_of_script += 'title.function("OverlayInput2Off")\n'
    end_of_script += 'powerpoint.function("Fade")\n\n'

    end_of_script += 'Else If (currentSlide >= firstReadingStart) and (currentSlide <= firstReadingEnd)\n'
    end_of_script += 'audio.function("AudioOff")\n'
    end_of_script += 'powerpoint.function("OverlayInput1In")\n'
    end_of_script += 'title.function("OverlayInput2Off")\n'
    end_of_script += 'firstReading.function("Play")\n\n'

    end_of_script += 'Else If (currentSlide = anthemStart)\n'
    end_of_script += 'audio.function("AudioOff")\n'
    end_of_script += 'powerpoint.function("OverlayInput1Off")\n'
    end_of_script += 'title.function("OverlayInput2Off")\n'
    end_of_script += 'anthem.function("Fade")\n'
    end_of_script += 'anthem.function("SetOutputFullscreen")\n\n'

    end_of_script += 'Else If (currentSlide >= secondReadingStart) and (currentSlide <= secondReadingEnd)\n'
    end_of_script += 'audio.function("AudioOff")\n'
    end_of_script += 'powerpoint.function("OverlayInput1In")\n'
    end_of_script += 'title.function("OverlayInput2Off")\n'
    end_of_script += 'secondReading.function("Play")\n\n'

    end_of_script += 'Else If (currentSlide = firstGospelVerse) then\n'
    end_of_script += 'powerpoint.function("SetOutputFullscreen")\n'
    end_of_script += 'camera.function("Fade")\n'
    end_of_script += 'powerpoint.function("OverlayInput1In")\n'
    end_of_script += 'title.function("OverlayInput2In")\n'
    end_of_script += 'audio.function("AudioOn")\n'
    end_of_script += 'firstHymn.function("AudioOff")\n'
    end_of_script += 'secondHymn.function("AudioOff")\n'
    end_of_script += 'gospelVerse.function("AudioOff")\n'
    end_of_script += 'thirdHymn.function("AudioOff")\n'
    end_of_script += 'Sleep(2000)\n'
    end_of_script += 'powerpoint.function("SetOutputFullscreen")\n'
    end_of_script += 'camera.function("Fade")\n'
    end_of_script += 'audio.function("AudioOff")\n'
    end_of_script += 'powerpoint.function("OverlayInput1In")\n'
    end_of_script += 'title.function("OverlayInput2In")\n'
    end_of_script += 'gospelVerse.function("Restart")\n'
    end_of_script += 'gospelVerse.function("AudioOn")\n'
    end_of_script += 'gospelVerse.function("Play")\n\n'

    end_of_script += 'Else If (currentSlide = secondGospelVerse) then\n'
    end_of_script += 'powerpoint.function("SetOutputFullscreen")\n'
    end_of_script += 'camera.function("Fade")\n'
    end_of_script += 'audio.function("AudioOff")\n'
    end_of_script += 'powerpoint.function("OverlayInput1In")\n'
    end_of_script += 'title.function("OverlayInput2In")\n'
    end_of_script += 'gospelVerse.function("Restart")\n'
    end_of_script += 'gospelVerse.function("AudioOn")\n'
    end_of_script += 'gospelVerse.function("Play")\n\n'

    end_of_script += 'Else If (currentSlide >= secondHymnStart and currentSlide < (secondHymnStart + secondHymnNumberOfVerses)) then\n'
    end_of_script += 'audio.function("AudioOff")\n'
    end_of_script += 'secondHymn.function("AudioOn")\n'
    end_of_script += 'secondHymn.function("Play")\n'
    end_of_script += 'powerpoint.function("OverlayInput1Off")\n'
    end_of_script += 'title.function("OverlayInput2Off")\n'
    end_of_script += 'powerpoint.function("Fade")\n\n'

    end_of_script += 'Else If (currentSlide >= thirdHymnStart and currentSlide < (thirdHymnStart + thirdHymnNumberOfVerses)) then\n'
    end_of_script += 'audio.function("AudioOff")\n'
    end_of_script += 'thirdHymn.function("AudioOn")\n'
    end_of_script += 'thirdHymn.function("Play")\n'
    end_of_script += 'powerpoint.function("OverlayInput1Off")\n'
    end_of_script += 'title.function("OverlayInput2Off")\n'
    end_of_script += 'powerpoint.function("Fade")\n\n'

    end_of_script += 'Else If (currentSlide >= fourthHymnStart and currentSlide < (fourthHymnStart + fourthHymnNumberOfVerses)) then\n'
    end_of_script += 'audio.function("AudioOff")\n'
    end_of_script += 'fourthHymn.function("AudioOn")\n'
    end_of_script += 'fourthHymn.function("Play")\n'
    end_of_script += 'powerpoint.function("OverlayInput1Off")\n'
    end_of_script += 'title.function("OverlayInput2Off")\n'
    end_of_script += 'powerpoint.function("Fade")\n\n'

    end_of_script += 'Else\n'
    end_of_script += 'If (streaming and currentSlide <> serviceEnd) then\n'
    end_of_script += 'powerpoint.function("SetOutputFullscreen")\n'
    end_of_script += 'camera.function("Fade")\n'
    end_of_script += 'powerpoint.function("OverlayInput1In")\n'
    end_of_script += 'title.function("OverlayInput2In")\n'
    end_of_script += 'audio.function("AudioOn")\n'
    end_of_script += 'firstHymn.function("AudioOff")\n'
    end_of_script += 'secondHymn.function("AudioOff")\n'
    end_of_script += 'gospelVerse.function("AudioOff")\n'
    end_of_script += 'thirdHymn.function("AudioOff")\n'
    end_of_script += 'End If\n'
    end_of_script += 'End If\n'
    end_of_script += 'End If\n'
    return end_of_script

end = open('end_of_script.txt', 'w')
end.write(get_end_text())
end.close()